CREATE TABLE CONTA(

ID INT PRIMARY KEY IDENTITY, 
VALOR MONEY NOT NULL,
TITULOS VARCHAR (100),
DATAINICIAL DATE ,
DATAFINAL DATE NOT NULL ,
INFORMACAO VARCHAR(100) NOT NULL,

);

CREATE TABLE CATEGORIA
(
ID INT PRIMARY KEY IDENTITY NOT NULL,
ESTUDO VARCHAR(100) NOT NULL,
CASA VARCHAR(100) NOT NULL,
PESSOAL VARCHAR(100) NOT NULL,
SAUDE VARCHAR(100) NOT NULL,
CONTAID INT FOREIGN KEY REFERENCES CONTA(ID) NOT NULL,
);

SELECT * FROM CONTA
SELECT * FROM CATEGORIA

drop table CONTA
drop table CATEGORIA